<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2021-06-13 10:51:08                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class InviteDAO extends AutoInviteDAO
	{
        /**
         * @param $invite
         * @return Invite
         * @throws ObjectNotFoundException
         */
        public function getByRequestedValue($invite) {
            return Invite::dao()->getByInvite($invite);
        }

        /**
         * @param $invite
         * @return Invite|null
         */
		public function getByInvite($invite)
		{
			return Criteria::create(Invite::dao())
				->add(Expression::eq(SQLFunction::create('lower', 'invite'), mb_strtolower($invite)))
				->setLimit(1)
				->get();
		}
	}
?>