<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2021-06-16 19:01:59                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class UserInvitesDAO extends OneToManyLinked
	{
		public function __construct(User $user, $lazy = false)
		{
			parent::__construct(
				$user,
				Invite::dao(),
				$lazy
			);
		}
		
		/**
		 * @return UserInvitesDAO
		**/
		public static function create(User $user, $lazy = false)
		{
			return new self($user, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'user_id';
		}
	}
?>