<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2021-07-10 19:07:54                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoRate extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Rate', 8, true, true, false, null, null),
				'post' => LightMetaProperty::fill(new LightMetaProperty(), 'post', 'post_id', 'identifier', 'Post', null, true, false, false, 1, 3),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'identifier', 'User', null, true, false, false, 1, 3),
				'liked' => LightMetaProperty::fill(new LightMetaProperty(), 'liked', null, 'boolean', null, null, true, true, false, null, null)
			);
		}
	}
?>