<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2021-06-13 11:32:45                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoInvite extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Invite', 8, true, true, false, null, null),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'identifier', 'User', null, true, false, false, 1, 3),
				'invite' => LightMetaProperty::fill(new LightMetaProperty(), 'invite', null, 'string', null, 128, true, true, false, null, null),
				'createdAt' => LightMetaProperty::fill(new LightMetaProperty(), 'createdAt', 'created_at', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'used' => LightMetaProperty::fill(new LightMetaProperty(), 'used', null, 'boolean', null, null, true, true, false, null, null),
				'usedBy' => LightMetaProperty::fill(new LightMetaProperty(), 'usedBy', 'used_by_id', 'identifier', 'User', null, false, false, false, 1, 3)
			);
		}
	}
?>