<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2021-07-10 19:07:54                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoRate extends IdentifiableObject
	{
		protected $post = null;
		protected $postId = null;
		protected $user = null;
		protected $userId = null;
		protected $liked = false;
		
		/**
		 * @return Post
		**/
		public function getPost()
		{
			if (!$this->post && $this->postId) {
				$this->post = Post::dao()->getById($this->postId);
			}
			
			return $this->post;
		}
		
		public function getPostId()
		{
			return $this->post
				? $this->post->getId()
				: $this->postId;
		}
		
		/**
		 * @return Rate
		**/
		public function setPost(Post $post)
		{
			$this->post = $post;
			$this->postId = $post ? $post->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return Rate
		**/
		public function setPostId($id)
		{
			$this->post = null;
			$this->postId = $id;
			
			return $this;
		}
		
		/**
		 * @return Rate
		**/
		public function dropPost()
		{
			$this->post = null;
			$this->postId = null;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function getUser()
		{
			if (!$this->user && $this->userId) {
				$this->user = User::dao()->getById($this->userId);
			}
			
			return $this->user;
		}
		
		public function getUserId()
		{
			return $this->user
				? $this->user->getId()
				: $this->userId;
		}
		
		/**
		 * @return Rate
		**/
		public function setUser(User $user)
		{
			$this->user = $user;
			$this->userId = $user ? $user->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return Rate
		**/
		public function setUserId($id)
		{
			$this->user = null;
			$this->userId = $id;
			
			return $this;
		}
		
		/**
		 * @return Rate
		**/
		public function dropUser()
		{
			$this->user = null;
			$this->userId = null;
			
			return $this;
		}
		
		public function getLiked()
		{
			return $this->liked;
		}
		
		public function isLiked()
		{
			return $this->liked;
		}
		
		/**
		 * @return Rate
		**/
		public function setLiked($liked = false)
		{
			$this->liked = ($liked === true);
			
			return $this;
		}
	}
?>