<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2021-06-13 10:51:08                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoInvite extends AutoProtoInvite {/*_*/}
?>