<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2021-07-10 19:07:54                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoRate extends AutoProtoRate {/*_*/}
?>