<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2021-07-10 19:07:55                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoRateDAO extends StorableDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'rate';
		}
		
		public function getObjectName()
		{
			return 'Rate';
		}
		
		public function getSequence()
		{
			return 'rate_id';
		}
	}
?>