<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2021-06-13 10:51:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoInviteDAO extends StorableDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'invite';
		}
		
		public function getObjectName()
		{
			return 'Invite';
		}
		
		public function getSequence()
		{
			return 'invite_id';
		}
	}
?>