<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2021-06-13 10:51:08                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Invite extends AutoInvite implements Prototyped, DAOConnected
	{
		/**
		 * @return Invite
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return InviteDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('InviteDAO');
		}
		
		/**
		 * @return ProtoInvite
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoInvite');
		}
		
		public function export()
		{
			$res =  [
				'id'		=> $this->getId(),
				'invite'	=> $this->getInvite(),
				'createdAt' => $this->getCreatedAt()->toStamp(),
				'used'		=> $this->isUsed(),
			];

			if ($this->getUsedBy()) {
				$res['usedBy'] = $this->getUsedBy()->getLogin();
			}

			return $res;
		}
	}
?>