<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2021-07-10 19:07:55                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Rate extends AutoRate implements Prototyped, DAOConnected
	{
		/**
		 * @return Rate
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return RateDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('RateDAO');
		}
		
		/**
		 * @return ProtoRate
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoRate');
		}
		
		// your brilliant stuff goes here
	}
?>